- name: Publish distrubtion to PyPI
  if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/rel`)
  uses: pypa/gh-action-pypi-publish@release/v1
  with:
    user: __token__
    password: ${{ secrets.PYPI_API_TOKEN }}
